<img src="img/Marca-ITBA-Color-ALTA.png" width="200">

# Programación para el Análisis de Datos

## Clase 2 - Numpy - ejercicios

In [49]:
import numpy as np

### Ejercicio 1

A partir de la lista de valores numéricos `l`, cree un array de NumPy `a`.

In [50]:
l = [3, 5, 10, 7]

### Completa con tu código aquí
a = np.array(l)
###
a

array([ 3,  5, 10,  7])

### Ejercicio 2

Reemplazar todos los números impares por el número $-1$


In [51]:
arr2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Completa con tu código aquí
arr2[arr2 % 2 != 0] = -1
###
print(arr2)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Ejercicio 3

A partir de los array 1D `x` e `y`, crear un array 1D `z` que sea el resultado de eliminar en `x` los elementos presentes en `y`.


**pista**
- ver la función [*setdiff1d*](https://numpy.org/doc/stable/reference/generated/numpy.setdiff1d.html)

In [52]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])

### Completa con tu código aquí
z = np.setdiff1d(x, y)

print(z)
####

[1 2 3 4]


### Ejercicio 4

Definir una función que obtiene los elementos de una matriz que sean mayores a 10 y multiplos de 3

In [53]:
def m10_mult3(X):
### Completa con tu código aquí
    return X[(X > 10) & (X % 3 == 0)]
###

A = np.arange(1000).reshape(5,-1)

m10_mult3(A)

array([ 12,  15,  18,  21,  24,  27,  30,  33,  36,  39,  42,  45,  48,
        51,  54,  57,  60,  63,  66,  69,  72,  75,  78,  81,  84,  87,
        90,  93,  96,  99, 102, 105, 108, 111, 114, 117, 120, 123, 126,
       129, 132, 135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165,
       168, 171, 174, 177, 180, 183, 186, 189, 192, 195, 198, 201, 204,
       207, 210, 213, 216, 219, 222, 225, 228, 231, 234, 237, 240, 243,
       246, 249, 252, 255, 258, 261, 264, 267, 270, 273, 276, 279, 282,
       285, 288, 291, 294, 297, 300, 303, 306, 309, 312, 315, 318, 321,
       324, 327, 330, 333, 336, 339, 342, 345, 348, 351, 354, 357, 360,
       363, 366, 369, 372, 375, 378, 381, 384, 387, 390, 393, 396, 399,
       402, 405, 408, 411, 414, 417, 420, 423, 426, 429, 432, 435, 438,
       441, 444, 447, 450, 453, 456, 459, 462, 465, 468, 471, 474, 477,
       480, 483, 486, 489, 492, 495, 498, 501, 504, 507, 510, 513, 516,
       519, 522, 525, 528, 531, 534, 537, 540, 543, 546, 549, 55

### Ejercicio 5

Escribir una función que reciba un array de numpy y sume todos los multiplos de 7 y 9 menores a 100

In [54]:
def sum_m7_m9(r):
    ### Completa con tu código aquí:
    return r[(r % 7 == 0) & (r % 9 == 0) & (r < 100)].sum()
    ###
    
a = np.arange(1, 200)

sum_m7_m9(a)

63

### Ejercicio 6

Crear una función que calcule la media movil con una ventana de largo 3.

**pista:**
- $$SMA = \frac{A_{n-2} + A_{n-1} + A_{n}}{3}$$
- Método [*cumsum*](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html)

In [55]:
### Completa con tu código aquí:
def media_movil(r, window_size):
    b = np.cumsum(r)
    b[window_size:] = b[window_size:] - b[:-window_size]
    return b[window_size - 1:] / window_size


a = np.random.randint(10, size=10)
print(a)

media_movil(a, 3)



[7 4 3 0 2 0 1 2 7 1]


array([4.66666667, 2.33333333, 1.66666667, 0.66666667, 1.        ,
       1.        , 3.33333333, 3.33333333])